List<String> sport = [
  'Select sport and event',
  'Ceremony',
  'Beach Volleyball',
  'Karate',
  'Athletics',
  'Football',
  'Rowing & Traditional Boat',
  'Volleyball',
  'Sport Climbing',
  'Tennis',
  'Badminton',
  'Fencing',
  'Chess',
  'Futsal',
  'Muay Thai',
  'Basketball',
  'Petanque',
  'Swimming',
  'Sepak Takraw',
  'Archery',
  'Pencak Silat',
  'Table Tennis',
  'E-sports',
  'Taekwondo',
  'Wushu',
];
