// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOx83yFNM27ypU5_DxnnQD_Br8kQwckzY',
    appId: '1:250816562493:web:80742cd9a077d396f1b154',
    messagingSenderId: '250816562493',
    projectId: 'seniorapplication-973df',
    authDomain: 'seniorapplication-973df.firebaseapp.com',
    storageBucket: 'seniorapplication-973df.appspot.com',
    measurementId: 'G-QC4HE2GE7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEv9JIzKJpJEzIQ-rCdaGO5rp6qWSzA1k',
    appId: '1:250816562493:android:f617adb69318c079f1b154',
    messagingSenderId: '250816562493',
    projectId: 'seniorapplication-973df',
    storageBucket: 'seniorapplication-973df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUbJCMB9rbQLS8051MQ3tMbwXJ7Z5Y3w',
    appId: '1:250816562493:ios:5c312c7397cc4228f1b154',
    messagingSenderId: '250816562493',
    projectId: 'seniorapplication-973df',
    storageBucket: 'seniorapplication-973df.appspot.com',
    iosClientId: '250816562493-tnfkseifm6oamhhkvok0oj568bdirojm.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorapp',
  );
}
